In [1]:
import pandas as pd
import numpy as np
import xarray as xr 

import sys
import datetime
import re
from datetime import date

In [2]:
### Define date to append to output file names
today = date.today()
run_date = today.strftime("%Y%m%d")

In [3]:
# load in master RCA instrument list
master_df = pd.read_csv('./params/RCA-InstrumentList.csv')

In [4]:
master_df

               assetID instrumentType  mfgSN SNnotes
0    ATOSU-69825-00001        ADCPS-I  21498     NaN
1    ATOSU-69825-00002        ADCPS-I  18153     NaN
2    ATOSU-69825-00003        ADCPS-I  18919     NaN
3    ATAPL-58419-00001        ADCPS-K  18444     NaN
4    ATAPL-58419-00002        ADCPS-K  18975     NaN
..                 ...            ...    ...     ...
399  ATAPL-71444-00003     DP-VEHICLE      3     NaN
400  ATAPL-71444-00004     DP-VEHICLE      4     NaN
401  ATAPL-71444-00005     DP-VEHICLE      5     NaN
402  ATAPL-71444-00006     DP-VEHICLE      6     NaN
403  ATAPL-71444-00007     DP-VEHICLE      7     NaN

[404 rows x 4 columns]

In [5]:
# load manual image overview CSV for the current year
imageSN_current = pd.read_csv('./inputs/imageSN_2024_draft.csv')
imageSN_past = pd.read_csv('./inputs/imageSN_2021_draft.csv')

In [6]:
#imageSN = pd.concat([imageSN_current, imageSN_past]) #TODO
imageSN = imageSN_current # unless you are loading in multiple years of image verification csvs

In [7]:
imageSN

,referenceDesignator,deployYear,imageFile,imageSerialNumber,imageAssetID
0,CE02SHBP-LJ01D-05-ADCPTB104,2020,IMG_4469.HEIC,19003,ATOSU-69826-00002
1,CE02SHBP-LJ01D-06-CTDBPN106,2020,IMG_4466.HEIC,7230,ATOSU-69827-00001
2,CE02SHBP-LJ01D-06-DOSTAD106,2020,IMG_4467.HEIC,216,ATOSU-58320-00020
3,CE02SHBP-LJ01D-07-VEL3DC108,2020,IMG_4468.HEIC,"5007,8167",ATOSU-69829-00003
4,CE02SHBP-LJ01D-08-OPTAAD106,2020,IMG_4465.HEIC,169,ATOSU-58332-00009
...,...,...,...,...,...
64,RS03AXPS-SF03A-3B-OPTAAD301,2020,IMG_1546.JPG,134,ATAPL-58332-00001
65,RS03AXPS-SF03A-3D-SPKIRA301,2020,IMG_1548.JPG,244,ATAPL-58341-00002
66,RS03AXPS-SF03A-4A-NUTNRA301,2020,IMG_1544.JPG,379,ATAPL-68020-00002
67,RS03AXPS-SF03A-4B-VELPTD302,2020,IMG_1544.JPG,6334,ATAPL-70114-00002
68,RS03AXPS-SF03A-4F-PCO2WA301,2020,IMG_1545.JPG,C0124,ATAPL-58336-00010

In [8]:
def process_mfgSN(row):
    # some assests have multiple manufacturer serial numbers so we split them out
    mfgSN_values = row['mfgSN'].split(',')
    assetID = row['assetID']
    
    return {mfgSN_value: assetID for mfgSN_value in mfgSN_values}

# Applying the function along rows (axis=1)
mfg_dict_list = master_df.apply(process_mfgSN, axis=1).to_list()

In [9]:
instrument_AT_dict = master_df.set_index('assetID')['instrumentType'].to_dict()
fuzzy_instrument_dict = {key: re.sub(r'[^a-zA-Z0-9]', '', value[:5]) for key, value in instrument_AT_dict.items()} #strip out anything thats not a letter or a number the "fuzzy" matching falls apart

In [10]:
fuzzy_instrument_dict

{'ATOSU-69825-00001': 'ADCPS',
 'ATOSU-69825-00002': 'ADCPS',
 'ATOSU-69825-00003': 'ADCPS',
 'ATAPL-58419-00001': 'ADCPS',
 'ATAPL-58419-00002': 'ADCPS',
 'ATAPL-58419-00003': 'ADCPS',
 'ATOSU-69826-00001': 'ADCPT',
 'ATOSU-69826-00002': 'ADCPT',
 'ATOSU-69826-00003': 'ADCPT',
 'ATAPL-58315-00001': 'ADCPT',
 'ATAPL-58315-00002': 'ADCPT',
 'ATAPL-58315-00003': 'ADCPT',
 'ATAPL-58315-00004': 'ADCPT',
 'ATAPL-58315-00005': 'ADCPT',
 'ATAPL-68073-00001': 'ADCPT',
 'ATAPL-68073-00002': 'ADCPT',
 'ATAPL-68073-00003': 'ADCPT',
 'ATAPL-68073-00004': 'ADCPT',
 'ATAPL-68073-00005': 'ADCPT',
 'PIRSN-PADCPA-00001': 'ADCPF',
 'ATAPL-58316-00001': 'BOTPT',
 'ATAPL-58316-00002': 'BOTPT',
 'ATAPL-58316-00003': 'BOTPT',
 'ATAPL-58316-00004': 'BOTPT',
 'ATAPL-58316-00005': 'BOTPT',
 'ATAPL-78437-00001': 'CAMDS',
 'ATAPL-78437-00002': 'CAMDS',
 'ATAPL-78437-00003': 'CAMDS',
 'ATAPL-78437-00004': 'CAMDS',
 'ATAPL-78437-00005': 'CAMDS',
 'ATAPL-78437-00006': 'CAMDS',
 'ATAPL-78437-00007': 'CAMDS',
 'ATAPL-78437-00008': 'CAMDS',
 'ATAPL-78437-00009': 'CAMDS',
 'ATAPL-78437-00010': 'CAMDS',
 'ATAPL-78437-00011': 'CAMDS',
 'ATAPL-78437-00012': 'CAMDS',
 'ATAPL-78437-00013': 'CAMDS',
 'ATAPL-58317-00001': 'CAMDS',
 'ATAPL-58317-00002': 'CAMDS',
 'ATAPL-58317-00003': 'CAMDS',
 'ATAPL-58317-00004': 'CAMDS',
 'ATAPL-58317-00005': 'CAMDS',
 'ATAPL-58317-00006': 'CAMDS',
 'ATAPL-58317-00009': 'CAMDS',
 'ATAPL-58317-00010': 'CAMDS',
 'ATAPL-58317-00011': 'CAMDS',
 'ATOSU-58317-00007': 'CAMDS',
 'ATOSU-58317-00008': 'CAMDS',
 'ATOSU-58317-00012': 'CAMDS',
 'ATOSU-58317-00013': 'CAMDS',
 'ATAPL-70248-00001': 'CAMHD',
 'ATAPL-70248-00002': 'CAMHD',
 'PIRSN-COVISA-00001': 'COVIS',
 'ATOSU-69827-00001': 'CTDBP',
 'ATOSU-69827-00002': 'CTDBP',
 'ATOSU-69827-00003': 'CTDBP',
 'ATAPL-69827-10004': 'CTDBP',
 'ATAPL-69827-10005': 'CTDBP',
 'ATOSU-69828-00001': 'CTDBP',
 'ATOSU-69828-00002': 'CTDBP',
 'ATOSU-69828-00003': 'CTDBP',
 'ATAPL-66662-00001': 'CTDPF',
 'ATAPL-66662-00002': 'CTDPF',
 'ATAPL-66662-00003': 'CTDPF',
 'ATAPL-66662-00004': 'CTDPF',
 'ATAPL-66662-00005': 'CTDPF',
 'ATAPL-66662-00008': 'CTDPF',
 'ATAPL-66662-00009': 'CTDPF',
 'ATAPL-66662-00010': 'CTDPF',
 'ATAPL-66662-00011': 'CTDPF',
 'ATAPL-66662-00012': 'CTDPF',
 'ATOSU-66662-00006': 'CTDPF',
 'ATOSU-66662-00007': 'CTDPF',
 'ATOSU-66662-00013': 'CTDPF',
 'ATOSU-66662-00014': 'CTDPF',
 'ATAPL-67627-00001': 'CTDPF',
 'ATAPL-67627-00002': 'CTDPF',
 'ATAPL-67627-00003': 'CTDPF',
 'ATAPL-67627-00004': 'CTDPF',
 'ATAPL-67627-00005': 'CTDPF',
 'ATCWK-67627-00006': 'CTDPF',
 'ATCWK-67627-00007': 'CTDPF',
 'ATCWK-67627-00008': 'CTDPF',
 'ATCWK-67627-00009': 'CTDPF',
 'ATCWK-67627-00010': 'CTDPF',
 'ATCWK-67627-00011': 'CTDPF',
 'ATCWK-67627-00012': 'CTDPF',
 'ATCWK-67627-00013': 'CTDPF',
 'ATAPL-67977-00001': 'CTDPF',
 'ATAPL-67977-00002': 'CTDPF',
 'ATAPL-67977-00003': 'CTDPF',
 'ATAPL-67977-00004': 'CTDPF',
 'ATAPL-67977-00005': 'CTDPF',
 'ATOSU-67977-00006': 'CTDPF',
 'ATOSU-67977-00007': 'CTDPF',
 'ATAPL-58694-00001': 'DOFST',
 'ATAPL-58694-00002': 'DOFST',
 'ATAPL-58694-00003': 'DOFST',
 'ATAPL-58694-00005': 'DOFST',
 'ATAPL-58694-00006': 'DOFST',
 'ATOSU-58694-00004': 'DOFST',
 'ATOSU-58694-00007': 'DOFST',
 'ATAPL-58320-00001': 'DOSTA',
 'ATAPL-58320-00002': 'DOSTA',
 'ATAPL-58320-00003': 'DOSTA',
 'ATAPL-58320-00004': 'DOSTA',
 'ATAPL-58320-00005': 'DOSTA',
 'ATAPL-58320-00006': 'DOSTA',
 'ATAPL-58320-00009': 'DOSTA',
 'ATAPL-58320-00010': 'DOSTA',
 'ATAPL-58320-00011': 'DOSTA',
 'ATAPL-58320-00012': 'DOSTA',
 'ATAPL-58320-00013': 'DOSTA',
 'ATAPL-58320-00014': 'DOSTA',
 'ATAPL-58320-00015': 'DOSTA',
 'ATAPL-58320-00016': 'DOSTA',
 'ATOSU-58320-00007': 'DOSTA',
 'ATOSU-58320-00008': 'DOSTA',
 'ATOSU-58320-00017': 'DOSTA',
 'ATOSU-58320-00018': 'DOSTA',
 'ATOSU-58320-00019': 'DOSTA',
 'ATOSU-58320-00020': 'DOSTA',
 'ATOSU-58320-00021': 'DOSTA',
 'ATOSU-58320-00022': 'DOSTA',
 'ATAPL-75664-00001': 'ENGPR',
 'ATAPL-75664-00002': 'ENGPR',
 'ATAPL-75664-00003': 'ENGPR',
 'ATAPL-75664-00004': 'ENGPR',
 'ATAPL-75664-00005': 'ENGPR',
 'ATAPL-75664-00006': 'ENGPR',
 'ATAPL-75664-00007': 'ENGPR',
 'ATAPL-70111-00001': 'FLCDR',
 'ATAPL-70111-00002': 'FLCDR',
 'ATAPL-70111-00003': 'FLCDR',
 'ATAPL-70111-00004': 'FLCDR',
 'ATAPL-70111-00005': 'FLCDR',
 'ATOSU-70111-00006': 'FLCDR',
 'ATOSU-70111-00007': 'FLCDR',
 'ATAPL-70110-00001': 'FLNTU',
 'ATAPL-70110-00002': 'FLNTU',
 'ATAPL-70110-00003': 'FLNTU',
 'ATAPL-70110-00004': 'FLNTU',
 'ATAPL-70110-00005': 'FLNTU',
 'ATOSU-70110-00006': 'FLNTU',
 'ATOSU-70110-00007': 'FLNTU',
 'ATAPL-58334-00001': 'FLOBN',
 'ATAPL-58334-00002': 'FLOBN',
 'ATAPL-58334-00003': 'FLOBN',
 'ATAPL-58334-00004': 'FLOBN',
 'ATAPL-70113-00001': 'FLOBN',
 'ATAPL-70113-00002': 'FLOBN',
 'ATAPL-70113-00003': 'FLOBN',
 'ATAPL-70113-00004': 'FLOBN',
 'ATAPL-58322-00001': 'FLOR',
 'ATAPL-58322-00002': 'FLOR',
 'ATAPL-58322-00003': 'FLOR',
 'ATAPL-58322-00004': 'FLOR',
 'ATAPL-58322-00005': 'FLOR',
 'ATAPL-58322-00006': 'FLOR',
 'ATAPL-58322-00007': 'FLOR',
 'ATAPL-58322-00009': 'FLOR',
 'ATAPL-58322-00010': 'FLOR',
 'ATAPL-58322-00011': 'FLOR',
 'ATAPL-58322-00012': 'FLOR',
 'ATAPL-58322-00014': 'FLOR',
 'ATOSU-58322-00008': 'FLOR',
 'ATOSU-58322-00013': 'FLOR',
 'ATAPL-58323-00001': 'HPIES',
 'ATAPL-58323-00002': 'HPIES',
 'ATAPL-58323-00003': 'HPIES',
 'ATAPL-58323-00004': 'HPIES',
 'ATAPL-58324-00001': 'HYDBB',
 'ATAPL-58324-00002': 'HYDBB',
 'ATAPL-58324-00003': 'HYDBB',
 'ATAPL-58324-00004': 'HYDBB',
 'ATAPL-58324-00005': 'HYDBB',
 'ATAPL-58324-00006': 'HYDBB',
 'ATAPL-58324-00007': 'HYDBB',
 'ATAPL-58324-00008': 'HYDBB',
 'ATAPL-58324-00009': 'HYDBB',
 'ATAPL-58324-00010': 'HYDBB',
 'ATAPL-58324-00011': 'HYDBB',
 'ATOSU-58324-00012': 'HYDBB',
 'ATOSU-58324-00013': 'HYDBB',
 'ATOSU-58324-00014': 'HYDBB',
 'ATOSU-58324-00015': 'HYDBB',
 'ATOSU-58324-00016': 'HYDBB',
 'PIRSN-HYDBBA-00001': 'HYDBB',
 'ATAPL-58693-00001': 'HYDLF',
 'ATAPL-58693-00002': 'HYDLF',
 'ATAPL-58693-00003': 'HYDLF',
 'ATAPL-58693-00004': 'HYDLF',
 'ATAPL-58693-00005': 'HYDLF',
 'ATAPL-58693-00006': 'HYDLF',
 'ATAPL-58693-00007': 'HYDLF',
 'PIRSN-CAMPIA-00001': 'MARUM',
 'PIRSN-CTDPFA-10001': 'MARUM',
 'PIRSN-CTDPFA-10002': 'MARUM',
 'PIRSN-OVRSRA-00001': 'MARUM',
 'PIRSN-QNTSRA-00001': 'MARUM',
 'ATAPL-58325-00001': 'MASSP',
 'ATAPL-58325-00002': 'MASSP',
 'ATAPL-58325-00003': 'MASSP',
 'ATAPL-58325-00004': 'MASSP',
 'ATAPL-68020-00001': 'NUTNR',
 'ATAPL-68020-00002': 'NUTNR',
 'ATAPL-68020-00003': 'NUTNR',
 'ATAPL-68020-00004': 'NUTNR',
 'ATAPL-68020-00006': 'NUTNR',
 'ATAPL-68020-00007': 'NUTNR',
 'ATOSU-68020-00005': 'NUTNR',
 'ATOSU-68020-00008': 'NUTNR',
 'ATAPL-58328-00001': 'OBSBB',
 'ATAPL-58328-00002': 'OBSBB',
 'ATAPL-58328-00003': 'OBSBB',
 'ATAPL-58328-00004': 'OBSBB',
 'ATAPL-58328-00005': 'OBSBB',
 'ATAPL-58329-00001': 'OBSBK',
 'ATAPL-58329-00002': 'OBSBK',
 'ATAPL-58331-00001': 'OBSSP',
 'ATAPL-58331-00002': 'OBSSP',
 'ATAPL-58331-00003': 'OBSSP',
 'ATAPL-58331-00004': 'OBSSP',
 'ATAPL-58331-00005': 'OBSSP',
 'ATAPL-58331-00006': 'OBSSP',
 'ATAPL-58331-00007': 'OBSSP',
 'ATAPL-58331-00008': 'OBSSP',
 'ATAPL-58331-00009': 'OBSSP',
 'ATAPL-58331-00010': 'OBSSP',
 'ATAPL-58331-00011': 'OBSSP',
 'ATAPL-69943-00001': 'OPTAA',
 'ATAPL-69943-00002': 'OPTAA',
 'ATAPL-69943-00003': 'OPTAA',
 'ATAPL-69943-00004': 'OPTAA',
 'ATAPL-69943-00005': 'OPTAA',
 'ATAPL-69943-00006': 'OPTAA',
 'ATAPL-69943-00007': 'OPTAA',
 'ATAPL-69943-00008': 'OPTAA',
 'ATAPL-69943-00009': 'OPTAA',
 'ATAPL-69943-00012': 'OPTAA',
 'ATOSU-69943-00010': 'OPTAA',
 'ATOSU-69943-00011': 'OPTAA',
 'ATAPL-58332-00001': 'OPTAA',
 'ATAPL-58332-00002': 'OPTAA',
 'ATAPL-58332-00004': 'OPTAA',
 'ATAPL-58332-00005': 'OPTAA',
 'ATAPL-58332-00006': 'OPTAA',
 'ATOSU-58332-00003': 'OPTAA',
 'ATOSU-58332-00007': 'OPTAA',
 'ATOSU-58332-00008': 'OPTAA',
 'ATOSU-58332-00009': 'OPTAA',
 'ATAPL-58333-00001': 'OSMOI',
 'ATAPL-58333-00002': 'OSMOI',
 'ATAPL-58333-00003': 'OSMOI',
 'ATAPL-58333-00004': 'OSMOI',
 'ATAPL-58333-00005': 'OSMOI',
 'ATAPL-66645-00001': 'PARAD',
 'ATAPL-66645-00002': 'PARAD',
 'ATAPL-66645-00003': 'PARAD',
 'ATAPL-66645-00004': 'PARAD',
 'ATAPL-66645-00006': 'PARAD',
 'ATAPL-66645-00007': 'PARAD',
 'ATOSU-66645-00005': 'PARAD',
 'ATOSU-66645-00008': 'PARAD',
 'ATAPL-78452-00001': 'PARAD',
 'ATAPL-78452-00002': 'PARAD',
 'ATAPL-78452-00003': 'PARAD',
 'ATAPL-78452-00004': 'PARAD',
 'ATAPL-78452-00005': 'PARAD',
 'ATAPL-78452-00006': 'PARAD',
 'ATAPL-78452-00007': 'PARAD',
 'ATAPL-58336-00001': 'PCO2W',
 'ATAPL-58336-00002': 'PCO2W',
 'ATAPL-58336-00003': 'PCO2W',
 'ATAPL-58336-00004': 'PCO2W',
 'ATAPL-58336-00009': 'PCO2W',
 'ATAPL-58336-00010': 'PCO2W',
 'ATOSU-58336-00005': 'PCO2W',
 'ATOSU-58336-00006': 'PCO2W',
 'ATOSU-58336-00007': 'PCO2W',
 'ATOSU-58336-00008': 'PCO2W',
 'ATOSU-70570-00001': 'PCO2W',
 'ATOSU-70570-00002': 'PCO2W',
 'ATOSU-70570-00003': 'PCO2W',
 'ATOSU-70570-00004': 'PCO2W',
 'ATAPL-58337-00001': 'PHSEN',
 'ATAPL-58337-00002': 'PHSEN',
 'ATAPL-58337-00003': 'PHSEN',
 'ATAPL-58337-00004': 'PHSEN',
 'ATAPL-58337-00005': 'PHSEN',
 'ATAPL-58337-00006': 'PHSEN',
 'ATAPL-58337-00009': 'PHSEN',
 'ATAPL-58337-00010': 'PHSEN',
 'ATAPL-58337-00013': 'PHSEN',
 'ATAPL-58337-00014': 'PHSEN',
 'ATOSU-58337-00007': 'PHSEN',
 'ATOSU-58337-00008': 'PHSEN',
 'ATOSU-58337-00011': 'PHSEN',
 'ATOSU-58337-00012': 'PHSEN',
 'ATOSU-70571-00001': 'PHSEN',
 'ATOSU-70571-00002': 'PHSEN',
 'ATOSU-70571-00003': 'PHSEN',
 'ATOSU-70571-00004': 'PHSEN',
 'ATAPL-58338-00001': 'PPSDN',
 'ATAPL-58338-00002': 'PPSDN',
 'ATAPL-58338-00003': 'PPSDN',
 'ATAPL-67639-00001': 'PREST',
 'ATAPL-67639-00002': 'PREST',
 'ATAPL-67639-00003': 'PREST',
 'ATAPL-67639-00004': 'PREST',
 'ATAPL-67639-00005': 'PREST',
 'ATAPL-67639-00006': 'PREST',
 'ATAPL-69923-00001': 'PREST',
 'ATAPL-69923-00002': 'PREST',
 'ATAPL-58340-00001': 'RASFL',
 'ATAPL-58340-00002': 'RASFL',
 'ATAPL-58340-00003': 'RASFL',
 'ATAPL-58341-00001': 'SPKIR',
 'ATAPL-58341-00002': 'SPKIR',
 'ATAPL-58341-00003': 'SPKIR',
 'ATAPL-58341-00004': 'SPKIR',
 'ATAPL-58341-00006': 'SPKIR',
 'ATAPL-58341-00007': 'SPKIR',
 'ATOSU-58341-00005': 'SPKIR',
 'ATOSU-58341-00008': 'SPKIR',
 'ATAPL-58342-00001': 'THSPH',
 'ATAPL-58342-00002': 'THSPH',
 'ATAPL-58342-00003': 'THSPH',
 'ATAPL-58343-00001': 'TMPSF',
 'ATAPL-58343-00002': 'TMPSF',
 'ATAPL-58343-00003': 'TMPSF',
 'ATAPL-67653-00001': 'TRHPH',
 'ATAPL-67653-00002': 'TRHPH',
 'ATAPL-67653-00003': 'TRHPH',
 'ATAPL-58345-00001': 'VADCP',
 'ATAPL-58345-00002': 'VADCP',
 'ATAPL-58345-00003': 'VADCP',
 'ATAPL-58345-00004': 'VADCP',
 'ATAPL-58345-00005': 'VADCP',
 'ATAPL-58345-00006': 'VADCP',
 'ATAPL-78520-00001': 'VADCP',
 'ATAPL-78520-00002': 'VACDP',
 'ATAPL-78520-00003': 'VADCP',
 'ATAPL-78520-00004': 'VADCP',
 'ATAPL-78520-00005': 'VADCP',
 'ATAPL-58346-00001': 'VEL3D',
 'ATAPL-58346-00002': 'VEL3D',
 'ATAPL-58346-00003': 'VEL3D',
 'ATAPL-58346-00004': 'VEL3D',
 'ATAPL-58346-00005': 'VEL3D',
 'ATAPL-58346-00006': 'VEL3D',
 'ATOSU-58346-00007': 'VEL3D',
 'ATOSU-58346-00008': 'VEL3D',
 'ATAPL-67979-00001': 'VEL3D',
 'ATAPL-67979-00002': 'VEL3D',
 'ATAPL-67979-00003': 'VEL3D',
 'ATAPL-67979-00004': 'VEL3D',
 'ATAPL-67979-00005': 'VEL3D',
 'ATAPL-67979-00006': 'VEL3D',
 'ATAPL-67979-00007': 'VEL3D',
 'ATAPL-67979-00008': 'VEL3D',
 'ATAPL-67979-00009': 'VEL3D',
 'ATAPL-67979-00010': 'VEL3D',
 'ATOSU-69829-00001': 'VEL3D',
 'ATOSU-69829-00002': 'VEL3D',
 'ATOSU-69829-00003': 'VEL3D',
 'ATOSU-69829-00004': 'VEL3D',
 'ATOSU-69829-00005': 'VEL3D',
 'ATAPL-70114-00001': 'VELPT',
 'ATAPL-70114-00002': 'VELPT',
 'ATAPL-70114-00003': 'VELPT',
 'ATAPL-70114-00004': 'VELPT',
 'ATAPL-70114-00006': 'VELPT',
 'ATAPL-70114-00007': 'VELPT',
 'ATOSU-70114-10005': 'VELPT',
 'ATOSU-70114-10008': 'VELPT',
 'PIRSN-AOABPA-00001': 'WILCO',
 'PIRSN-AOABPA-10001': 'WILCO',
 'PIRSN-FETCHA-00001': 'WILCO',
 'PIRSN-FETCHA-00002': 'WILCO',
 'PIRSN-SCPRAA-00001': 'WILCO',
 'PIRSN-SCTAAA-00001': 'WILCO',
 'ATOSU-63259-00001': 'ZPLSC',
 'ATOSU-63259-00002': 'ZPLSC',
 'ATOSU-63259-00003': 'ZPLSC',
 'ATOSU-63259-00004': 'ZPLSC',
 'ATOSU-63259-00005': 'ZPLSC',
 'ATAPL-90485-20001': 'ZPLSC',
 'ATAPL-90485-20002': 'ZPLSC',
 'ATAPL-90485-20004': 'ZPLSC',
 'ATAPL-90485-20005': 'ZPLSC',
 'ATAPL-71532-00001': 'DPDO',
 'ATAPL-71532-00002': 'DPDO',
 'ATAPL-71532-00003': 'DPDO',
 'ATAPL-71532-00004': 'DPDO',
 'ATAPL-71532-00005': 'DPDO',
 'ATAPL-71444-00001': 'DPVE',
 'ATAPL-71444-00002': 'DPVE',
 'ATAPL-71444-00003': 'DPVE',
 'ATAPL-71444-00004': 'DPVE',
 'ATAPL-71444-00005': 'DPVE',
 'ATAPL-71444-00006': 'DPVE',
 'ATAPL-71444-00007': 'DPVE'}

In [11]:
mfg_dict_list[:20]

[{'21498': 'ATOSU-69825-00001'},
 {'18153': 'ATOSU-69825-00002'},
 {'18919': 'ATOSU-69825-00003'},
 {'18444': 'ATAPL-58419-00001'},
 {'18975': 'ATAPL-58419-00002'},
 {'18977': 'ATAPL-58419-00003'},
 {'18493': 'ATOSU-69826-00001'},
 {'19003': 'ATOSU-69826-00002'},
 {'22115': 'ATOSU-69826-00003'},
 {'18478': 'ATAPL-58315-00001'},
 {'18974': 'ATAPL-58315-00002'},
 {'18980': 'ATAPL-58315-00003'},
 {'23338': 'ATAPL-58315-00004'},
 {'23339': 'ATAPL-58315-00005'},
 {'18471': 'ATAPL-68073-00001'},
 {'18813': 'ATAPL-68073-00002'},
 {'19224': 'ATAPL-68073-00003'},
 {'23442': 'ATAPL-68073-00004'},
 {'23443': 'ATAPL-68073-00005'},
 {'1023': 'PIRSN-PADCPA-00001'}]

In [12]:
def instrument_type_sanity_check(instrument, possible_asset_tag, inst_dict):
    instrument_type = inst_dict[possible_asset_tag]

    if instrument_type in instrument:
        print(f"{instrument_type} for possible AT {possible_asset_tag} matches {instrument}")
        return True
    else: 
        print(f"{instrument_type} for possible AT {possible_asset_tag} DOES NOT match {instrument}")
        return False

In [13]:
def process_imageSN(row, mfg_dict_list, inst_dict):
    
    print('-----------------------------------------------')
    imageSerialNumbers = row['imageSerialNumber']
    imageAssetID = row['imageAssetID']
    instrument = row['referenceDesignator'][18:]
    print(instrument)
    
    if type(imageSerialNumbers) is str and '/' in imageSerialNumbers:
        imageSerialNumbers = row['imageSerialNumber'].split('/')
        print(f"it looks like there are multiple / SNs in this cell {imageSerialNumbers}")
    elif type(imageSerialNumbers) is str and ',' in imageSerialNumbers:
        imageSerialNumbers = row['imageSerialNumber'].split(',')
        print(f"it looks like there are multiple , SNs in this cell {imageSerialNumbers}")
    else:
        imageSerialNumbers = [imageSerialNumbers] # both list for consistency

    # list of matching asset ids
    match_list = []
    # proportion of serial number which matches if it is a partial match
    prop_list = []
    # list of the manufacturer serial numbers that match the imageSN
    mfg_sn_list = []

    # exact SN match
    exact_match_found = False 
    # assetID, exact SN or partial SN match
    any_match_found = False
    # exact assetID match
    exact_asset_match_found = False
    # any assetID match
    any_asset_match_found = False

    # extract lists of mfg serial numbers and asset tags from mfg_dict_list
    
    for imageSerialNumber in imageSerialNumbers:
        print(f"matching {imageSerialNumber}...")
        for SN_AT_dict in mfg_dict_list:
            for manufacturerSerialNumber in SN_AT_dict.keys():
                if type(imageSerialNumber) is str and imageSerialNumber == manufacturerSerialNumber:
                    matching_assetID = SN_AT_dict[manufacturerSerialNumber]
                    if instrument_type_sanity_check(instrument, matching_assetID, inst_dict):
                        print("exact match found and sanity check passed")
                        match_list.append(matching_assetID)
                        mfg_sn_list.append(manufacturerSerialNumber)
    
                        match_list = list(set(match_list))
        
                        exact_match_found = True
                        any_match_found = True
            
        if exact_match_found == False:
            for SN_AT_dict in mfg_dict_list:
                for manufacturerSerialNumber in SN_AT_dict.keys():
                    if type(imageSerialNumber) is str and imageSerialNumber in manufacturerSerialNumber and imageSerialNumber != manufacturerSerialNumber:
                        matching_assetID = SN_AT_dict[manufacturerSerialNumber]
                        if instrument_type_sanity_check(instrument, matching_assetID, inst_dict):
                            print("found a partial match and sanity check passed")
                            match_prop = round(len(imageSerialNumber) / len(manufacturerSerialNumber),2)
                            match_list.append(matching_assetID)
                            prop_list.append(match_prop)
                            mfg_sn_list.append(manufacturerSerialNumber)
        
                            match_list = list(set(match_list))
            
                            any_match_found = True

        
        if any_match_found == False:
            print(f"still no match - attempting to match by assetID <{imageAssetID}> instead...")
            for SN_AT_dict in mfg_dict_list:
                for master_assetID in SN_AT_dict.values():
                    if type(imageAssetID) is str and imageAssetID == master_assetID:
                        if instrument_type_sanity_check(instrument, imageAssetID, inst_dict):
                            print("exact assetID match found from image SN, and sanity check passed")
                            matching_assetID = master_assetID
                            match_list.append(matching_assetID)
        
                            match_list = list(set(match_list))
            
                            any_match_found = True
                            exact_asset_match_found = True
                
            
    if len(match_list) > 0:
        row['matching_asset_ids'] = match_list
    else: 
        row['matching_asset_ids'] = np.nan

    if len(prop_list) > 0: 
        row['proportion_match'] = prop_list
    else: 
        row['proportion_match'] = np.nan

    if len(mfg_sn_list) > 0:
        row['matching_mfg_sn'] = mfg_sn_list
    else:
        row['matching_mfg_sn'] = np.nan

    if exact_match_found == False:
        row["exact_SN_match"] = np.nan
    else:
        row["exact_SN_match"] = True

    if exact_asset_match_found == False:
        row["exact_assetID_match"] = np.nan
    else:
        row["exact_assetID_match"] = True

    if any_match_found == False:
        row["any_match"] = np.nan
    else:
        row["any_match"] = True

    return row

In [14]:
log_file_path = 'logs/fuzzy_match_log.txt'
with open(log_file_path, 'w') as log_file:
    # Save the current stdout so we can restore it later
    original_stdout = sys.stdout
    sys.stdout = log_file
    
    imageSN = imageSN.apply(process_imageSN, axis=1, args=(mfg_dict_list, fuzzy_instrument_dict))

    sys.stdout = original_stdout
print("logs printed to logs directory")

logs printed to logs directory

In [15]:
imageSN.head()

,referenceDesignator,deployYear,imageFile,imageSerialNumber,imageAssetID,matching_asset_ids,proportion_match,matching_mfg_sn,exact_SN_match,exact_assetID_match,any_match
0,CE02SHBP-LJ01D-05-ADCPTB104,2020,IMG_4469.HEIC,19003,ATOSU-69826-00002,[ATOSU-69826-00002],NaN,[19003],True,NaN,True
1,CE02SHBP-LJ01D-06-CTDBPN106,2020,IMG_4466.HEIC,7230,ATOSU-69827-00001,[ATOSU-69827-00001],[0.31],[16P71176-7230],NaN,NaN,True
2,CE02SHBP-LJ01D-06-DOSTAD106,2020,IMG_4467.HEIC,216,ATOSU-58320-00020,[ATOSU-58320-00020],NaN,[216],True,NaN,True
3,CE02SHBP-LJ01D-07-VEL3DC108,2020,IMG_4468.HEIC,"5007,8167",ATOSU-69829-00003,[ATOSU-69829-00003],"[0.5, 0.44]","[VEC-5007, VEC-8167]",NaN,NaN,True
4,CE02SHBP-LJ01D-08-OPTAAD106,2020,IMG_4465.HEIC,169,ATOSU-58332-00009,[ATOSU-58332-00009],NaN,[169],True,NaN,True

In [16]:
imageSN.to_csv(f"./reportOuts/fuzzyMatches_{run_date}_2020.csv")
imageSN_HITL = imageSN
imageSN_HITL['HITL_match_notes'] = pd.Series(dtype='object')
imageSN_HITL.to_csv(f"./reportOuts/fuzzyMatches_HITL_{run_date}_2020.csv")

## NOTE: Now we have to manually go through the fuzzy matches HITL csv and correct multiply matches, account for missing AssetIDs and serial numbers.